services:
  api:
    build:
      context: ./services/api
    env_file:
      - path: ./services/api/.env.local
        required: false
    environment:
      HTTP_ADDR: ":8080"
      BASE_URL: "http://localhost:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./services/api:/app
      - ~/.aws:/root/.aws:ro
      - go-mod-cache:/go/pkg/mod

volumes:
  go-mod-cache:
